Rename multiplex to libp2p-multiplex
libp2p/rust-libp2p pull request #153
Opened 2018-03-20 16:00 UTC by tomaka

Close #151

2018-03-20 17:39 UTC, daviddias requested changes

2018-03-20 17:39 UTC, diasdavid commented on example/Cargo.toml
> +libp2p-multiplex = { path = "../multiplex" }
actually, rename to libp2p-mplex. See the new spec https://github.com/libp2p/mplex

2018-03-21 09:28 UTC, Vurich commented
I don't think `multiplex` has anything to do with `libp2p` necessarily. It's just a Rust implementation of the JS `multiplex` library

2018-03-21 09:38 UTC, tomaka commented
It's tied to the other parts of libp2p though. For example it implements the `ConnectionReuse` trait.

2018-05-02 08:35 UTC, tomaka commented
@diasdavid I renamed this to `mplex`, could you accept the changes? :)

2018-05-04 10:38 UTC, tomaka commented
I don't understand why the master branch passes CI, meanwhile this PR doesn't because the version of Rust is too old.

2018-05-04 10:50 UTC, daviddias approved these changes

2018-05-04 10:50 UTC, diasdavid commented
@VictorBjelkholm wanna help the rust team running their tests on Jenkins as well?

2018-05-04 10:57 UTC, VictorBjelkholm commented
@diasdavid Sure, I'd be happy to help! Created issue for tracking it here: https://github.com/ipfs/jenkins-libs/issues/11

2018-05-04 11:13 UTC, tomaka commented
Why is Jenkins needed, however? I was in fact thinking of ditching travis so that we only have to deal with one CI infrastructure.

2018-05-04 11:44 UTC, VictorBjelkholm commented
@tomaka we're using jenkins across all ipfs, libp2p, multiformats, ipld and ipfs-shipyard. Basically the main features at this point would be faster builds, easier maintenance of pipelines, automatically add projects to jenkins by just adding a file in `ci/Jenkinsfile` and it'll automatically pick up, test results nicely highlighted ([example](https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs/detail/master/88/tests)), cross-platform builds (win, mac, linux and more to come in the future) in one CI service and some other minor benefits. In general, it's pretty good.

2018-05-04 13:27 UTC, merged