protocols/relay/examples: Add client server instructions
libp2p/rust-libp2p pull request #2060
Opened 2021-04-28 09:57 UTC by mxinden

Add instructions on how to run a three node example where a listening
relay client listens via a relay server and a dialing relay client dials
the listening relay client via the relay server.

//CC @r-zig

2021-04-28 18:50 UTC, r-zig requested changes
I think that the 3 client (the dial one) command should be with client-dial argument instead of client-listen and add /p2p/ before the listening client peer id:
`cargo run --example relay -- client-**dial**<addr-relay-server>/p2p/<peer-id-relay-server>/p2p-circuit/**p2p/**<peer-id-listening-relay-client>

2021-04-28 19:13 UTC, r-zig requested changes

2021-04-28 19:13 UTC, r-zig commented on protocols/relay/examples/relay.rs
> +//! <addr-relay-server>/p2p/<peer-id-relay-server>/p2p-circuit/<peer-id-listening-relay-client>` in
suppose that the relay peer id is: QmRelay and the relay peer address is /ip6/::1/tcp/54443
the listening peer id is:  QmListenPeer

cargo run --example relay -- client-dial /ip6/::1/tcp/54443/p2p/QmRelay/p2p-circuit/p2p/QmListenPeer

2021-04-29 12:40 UTC, mxinden commented
Good catch @r-zig. I pushed another commit. Want to take another look?

2021-05-04 17:21 UTC, mxinden commented
@vmx could you give this pull request a review as a member of the libp2p Rust team?

2021-05-10 12:58 UTC, mxinden commented
@vmx thanks for the review. Would you mind taking another look?

2021-05-10 13:00 UTC, vmx approved these changes
Nice! To me that reads really clear now.

2021-05-10 13:39 UTC, merged