CI updates
libp2p/rust-libp2p pull request #2228
Opened 2021-09-10 19:34 UTC by TriplEight

- cancel previous runs
- update `styfle/cancel-workflow-action` version
- add `github-actions` versioning to Dependabot
- experiment with `clang-11`, simply because 10 is weirdly broken in ubuntu
- `Swatinem/rust-cache` handles Rust cache better

2021-09-14 14:05 UTC, kpp commented
There is no need to fix CI, it works: https://github.com/libp2p/rust-libp2p/pull/2227/checks

2021-09-16 03:25 UTC, thomaseizinger requested changes
A few nits but otherwise a welcoming change from my end. Personally I've had a good experience with `rust-cache` so far!

2021-09-16 03:25 UTC, thomaseizinger commented on .github/workflows/ci.yml
> +
Seems like an unnecessary diff.

2021-09-16 03:25 UTC, thomaseizinger commented on .github/workflows/ci.yml
> +    - uses: Swatinem/rust-cache@v1
Same as with the `checkout` action, specifying the full version will avoid a direct dependabot PR after this is merged.

2021-09-16 08:11 UTC, TriplEight commented on .github/workflows/ci.yml
> -        echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" >> /etc/apt/sources.list
yeah, it's not needed anymore.

2021-09-16 08:20 UTC, TriplEight commented on .github/workflows/ci.yml
> +    - uses: actions/checkout@v2
you're right

2021-09-16 09:21 UTC, thomaseizinger approved these changes
Thanks, this looks good!

We will have to wait for @mxinden to merge this. He is currently on vacation though so that might take a little longer :)

2021-09-25 13:21 UTC, mxinden approved these changes
Thank you @TriplEight. Very much appreciate your help here! Good to have a GitHub CI expert around.

2021-09-25 13:22 UTC, merged