"Just works" WASM experience
libp2p/rust-libp2p pull request #2245
Opened 2021-09-22 19:28 UTC by wngr

These are the changes I needed to make in order to get libp2p to run via WASM in the browser (both main thread and inside web workers).

* The only occurrence left of `wasm-timer` is in `gossipsub`, as it uses an `Interval`. Haven't gotten around to refactor that (yet).
* The other thing is that I'm waiting for a release of the instant create (see https://github.com/sebcrozet/instant/pull/36).

Looking for comments, whether this is something that can get merged, or whether there are alternative approaches.

related #2134 #2166 #2143

2021-09-29 10:16 UTC, mxinden commented
@wngr very very very much appreciated! I am sorry for the delay here. I will give this a review. I just need a bit more time.

2021-10-04 16:59 UTC, mxinden reviewed
Just a couple of comments for now. Let me know if you need help pinging folks for https://github.com/sebcrozet/instant/pull/9.

Again, thanks for this contribution!

2021-10-04 16:59 UTC, mxinden commented on .github/workflows/ci.yml
> +    - name: Build on wasm32-wasi
```suggestion
    - name: Build on wasm32-unknown-unknown
```

2021-10-04 16:59 UTC, mxinden commented on Cargo.toml
> +structopt = "0.3.23"
Is this version bump needed?

2021-10-04 16:59 UTC, mxinden commented on Cargo.toml
> +getrandom = "0.2.3"
Do I understand correctly that the crate needs to be listed here in order to enable the `js` feature? If so, would you mind adding a comment? Same for the other crates?

2021-10-04 16:59 UTC, mxinden commented on core/src/lib.rs
> +pub use instant::{Duration, Instant};
If I am not mistaken this is the first non-libp2p-related re-export in `libp2p-core`, correct?

If so, I wonder whether it is actually needed. Neither of these two types are exposed on the public API of `libp2p-core`, right? Do versions actually have to match across libp2p crates?

2021-10-04 16:59 UTC, mxinden commented on .github/workflows/ci.yml
> +      # TODO: also run `cargo test`
Yes please, that would be great!

2021-10-06 07:01 UTC, thomaseizinger requested changes
Thank you!

Some comments inline, nothing big :)

2021-10-06 07:01 UTC, thomaseizinger commented on .github/workflows/ci.yml
> +        override: true
These CI jobs changed recently with https://github.com/libp2p/rust-libp2p/pull/2260. Can you merge latest master and adapt accordingly?

2021-10-06 07:01 UTC, thomaseizinger commented on Cargo.toml
> +structopt = "0.3.23"
I don't think it is a version bump per-se. cargo would have already resolved anything > 0.3.21 for the target binary if needed. I usually tend to only specify these to the minor version for that reason, ie:

```toml
structopt = "0.3"
```

2021-10-06 07:01 UTC, thomaseizinger commented on core/src/lib.rs
> +pub use instant::{Duration, Instant};
+1 for not re-exporting. We shouldn't pull this in unless necessary.

2021-10-06 07:01 UTC, thomaseizinger commented on transports/wasm-ext/src/websockets.js
> +          // The passed in `data` is an `ArrayBufferView` [0]. If the
This file seems to be tab-indented but the new code here is using spaces which I think is why this is rendering as un-aligned?

2021-10-10 18:35 UTC, wngr commented on core/src/lib.rs
> +pub use instant::{Duration, Instant};
so you're saying that all relevant crates should depend on `instant` directly, and not go via the indirection through `core` proposed here -- right?

2021-10-10 18:47 UTC, wngr commented on Cargo.toml
> +structopt = "0.3.23"
No, not needed. I guess I ran `cargo update` at some point. Should I revert the _unnecessary_ changes?

2021-10-10 18:55 UTC, wngr commented on transports/wasm-ext/src/websockets.js
> +          // The passed in `data` is an `ArrayBufferView` [0]. If the
Right, now it should be aligned.

2021-10-11 08:30 UTC, mxinden commented on Cargo.toml
> +structopt = "0.3.23"
> Should I revert the unnecessary changes?

Yes please.

---

Strategy for rust-libp2p as a library is: Bump minor version (patch version on < v1.0.0) only:

- on bug fixes
- on security fixes
- when a specific feature within the minor (patch) release is needed within rust-libp2p

This makes rust-libp2p compatible with a larger range of upstream crates and thus gives downstream users greater flexibility.

(Obviously I highly recommend downstream binaries to keep their upstream dependencies up-to-date.)

2021-10-11 08:33 UTC, mxinden commented on core/src/lib.rs
> +pub use instant::{Duration, Instant};
Yes. That would be my preference, especially since, as far as I can tell, versions of `instant` don't have to match across crates, as `instant` is not exposed on the public `libp2p-core` interface.

2021-10-16 17:56 UTC, wngr commented on .github/workflows/ci.yml
> +      # TODO: also run `cargo test`
That's a bigger undertaking, which might be more geared towards `wasm32-wasi` rather than `wasm32-unknown-unknown`.
I guess for `wasm32-unknown-unknown` a wasm-bindgen based browser smoke test might be something, but I'll leave that to future-us :-)

2021-10-16 18:00 UTC, wngr commented on core/src/lib.rs
> +pub use instant::{Duration, Instant};
:+1: done

2021-10-16 18:00 UTC, wngr commented on Cargo.toml
> +structopt = "0.3.23"
Thanks for your detailled response, reverted all unrelated changes.

2021-10-16 18:02 UTC, wngr commented on Cargo.toml
> +instant = { git = "https://github.com/wngr/instant", branch = "systemtime" }
pending https://github.com/sebcrozet/instant/pull/42

2021-10-16 18:09 UTC, wngr commented
I think the test failure is unrelated to this PR.

2021-10-18 11:49 UTC, wngr commented
Should be good to go for another :eyes: @mxinden @thomaseizinger

2021-10-18 16:14 UTC, mxinden commented
> I think the test failure is unrelated to this PR.

Yes. Fixed once https://github.com/libp2p/rust-libp2p/pull/2295 is merged.

2021-10-19 07:47 UTC, thomaseizinger approved these changes
Thanks!

Made a few suggestions but nothing blocking.

2021-10-19 07:47 UTC, thomaseizinger commented on .github/workflows/ci.yml
> +    - name: Build on ${{ matrix.toolchain }}
Instead of making two jobs that only differ in their features, we could add the matrix like this:

```yaml
matrix:
  toolchain: [
    wasm32-unknown-emscripten,
    wasm32-wasi
  ]
  include:
     - toolchain: wasm32-unknown-unknown
       args: "--features wasm-bindgen"
```

And then do:

```yaml
- name: Build on ${{ matrix.toolchain }}
  run: cargo build --target=${{ matrix.toolchain }} ${{ matrix.args }}
```

That will work because GitHub actions replaces non-existent matrix keys with an empty string.

2021-10-19 07:47 UTC, thomaseizinger commented on Cargo.toml
> +futures-timer = "3.0.2"
Can we have the comment _next_ to the dependency? That way it is a single line and the table can more easily be sorted alphabetically.

```suggestion
futures-timer = "3.0.2" # Explicit dependency to be used in `wasm-bindgen` feature
```

2021-10-19 07:47 UTC, thomaseizinger commented on protocols/gossipsub/src/interval.rs
> +        .and_then(|v| v.checked_add(dur.subsec_nanos() as u64))
Nit: This could use `?` to propagate the `None` case instead of combinators.

2021-10-21 08:09 UTC, PhilippGackstatter commented
Great PR! Getting rid of `wasm-timer` in favor of `instant` is much appreciated. Do these changes rely on any browser-exclusive APIs (haven't checked what `futures-timer/wasm-bindgen` binds to) or would this also work in node.js?

2021-10-21 11:38 UTC, wngr commented
I think `futures-timer`(uses `gloo-timers` under the hood) indeed does not work inside nodejs, but I've never tried it.

2021-10-22 10:14 UTC, mxinden commented
Thanks for the pull request @wngr!

As you might have seen, we already cut a `v0.40.0` release candidate, thus this pull request would be included in `v0.41.0`. In case you need a release quickly, I am happy to prepare `v0.41.0` shortly after `v0.40.0` is released.

2021-10-30 10:42 UTC, mxinden commented
Merged via https://github.com/libp2p/rust-libp2p/pull/2320. Thanks @wngr for the work!

2021-10-30 10:42 UTC, closed without merging

2021-11-12 18:36 UTC, wngr commented
> Thanks for the pull request @wngr!
> 
> As you might have seen, we already cut a `v0.40.0` release candidate, thus this pull request would be included in `v0.41.0`. In case you need a release quickly, I am happy to prepare `v0.41.0` shortly after `v0.40.0` is released.

Would appreciate if you could cut create a `v0.41.0` soon-ish!