Adding impls for std::error::Error on error types in gossipsub
libp2p/rust-libp2p pull request #2254
Opened 2021-09-29 19:48 UTC by McFranko

It's annoying to work with these error types, because they can't be used with the `?` operator. This fixes that

2021-09-30 04:08 UTC, thomaseizinger requested changes
Thanks!

Can you add a changelog entry please?

2021-09-30 04:08 UTC, thomaseizinger commented on protocols/gossipsub/src/error.rs
> +impl std::error::Error for PublishError {}
`PublishError` has two variants that contain a source, can we override `source` for these please?

2021-09-30 04:08 UTC, thomaseizinger commented on protocols/gossipsub/src/error.rs
> +impl std::error::Error for SubscriptionError {}
Same here, please override `source` and return `PublishError` there.

2021-09-30 23:53 UTC, thomaseizinger commented on protocols/gossipsub/CHANGELOG.md
> +
```suggestion
  [PR 2254](https://github.com/libp2p/rust-libp2p/pull/2254)

```

2021-09-30 23:54 UTC, thomaseizinger commented on protocols/gossipsub/CHANGELOG.md
> +- Added std::error::Error impls for error types
```suggestion
- Implement std::error::Error for error types.
```

2021-09-30 23:54 UTC, thomaseizinger approved these changes
Thanks!

2021-10-01 16:22 UTC, mxinden approved these changes
Thanks @McFranko

2021-10-01 16:23 UTC, merged