Update rustls 0.20
libp2p/rust-libp2p pull request #2299
Opened 2021-10-16 11:02 UTC by quininer

2021-10-17 23:58 UTC, thomaseizinger requested changes
One comment, otherwise LGTM!

Can you please address the clippy lint failure?

2021-10-17 23:58 UTC, thomaseizinger commented on transports/websocket/src/tls.rs
> +            .with_no_client_auth();
I am not 100% what should be happening here but does this make sense if we are constructing a _client_ `Config` here?

2021-10-17 23:58 UTC, thomaseizinger commented on transports/websocket/src/tls.rs
> +            .with_no_client_auth();
Same here.

2021-10-18 02:35 UTC, quininer commented on transports/websocket/src/tls.rs
> +            .with_no_client_auth();
I'm not sure, I just translated the old code as is.

2021-10-18 02:54 UTC, thomaseizinger commented on transports/websocket/src/tls.rs
> +            .with_no_client_auth();
The old code only sets `NoClientAuth` within the `server` constructor (line 108).

For `client`, we don't set anything (line 89).

2021-10-18 03:21 UTC, quininer commented on transports/websocket/src/tls.rs
> +            .with_no_client_auth();
`NoClientAuth` is the default value in rustls 0.19, but in rustls 0.20 you need to set it explicitly.

2021-10-18 04:26 UTC, thomaseizinger commented on transports/websocket/src/tls.rs
> +            .with_no_client_auth();
Right, thanks for clarifying!

2021-11-14 22:27 UTC, mxinden commented
Replaced with https://github.com/libp2p/rust-libp2p/pull/2336. Thanks @quininer for the help!

2021-11-14 22:27 UTC, closed without merging