Drop `atomic` dependency
libp2p/rust-libp2p pull request #2643
Opened 2022-05-11 13:10 UTC by hrxi

Replace `atomic::Atomic<u64>` by `std::sync::atomic:AtomicU64`.

2022-05-11 23:09 UTC, thomaseizinger requested changes
Thanks for the contribution!

1. Can you write a few lines about this change? i.e. is the `atomic` crate fully superseded by the std lib?
2. We don't have a lockfile checked into the repository because we are only developing a library here. Can you post the output of `cargo tree -i -p atomic` to show that we are actually dropping the dependency?

2022-05-11 23:31 UTC, hrxi commented
> 1. Can you write a few lines about this change? i.e. is the `atomic` crate fully superseded by the std lib?

Done.

> 2. We don't have a lockfile checked into the repository because we are only developing a library here. Can you post the output of `cargo tree -i -p atomic` to show that we are actually dropping the dependency?

```
$ git checkout pr_drop_atomic
Previous HEAD position was f04f6bb4 identify/handler: Improve property name (#2639)
Switched to branch 'pr_drop_atomic'
$ cargo tree -i -p atomic
error: package ID specification `atomic` did not match any packages

	Did you mean `tokio`?
$ git checkout HEAD~
HEAD is now at f04f6bb4 identify/handler: Improve property name (#2639)
$ cargo tree -i -p atomic | head
atomic v0.5.1
├── libp2p v0.45.0 (/home/u/nimiq/rust-libp2p)
│   [dev-dependencies]
│   ├── libp2p-autonat v0.4.0 (/home/u/nimiq/rust-libp2p/protocols/autonat)
│   │   └── libp2p v0.45.0 (/home/u/nimiq/rust-libp2p) (*)
│   ├── libp2p-dcutr v0.3.0 (/home/u/nimiq/rust-libp2p/protocols/dcutr)
│   │   ├── libp2p v0.45.0 (/home/u/nimiq/rust-libp2p) (*)
│   │   └── libp2p-metrics v0.6.0 (/home/u/nimiq/rust-libp2p/misc/metrics)
│   │       └── libp2p v0.45.0 (/home/u/nimiq/rust-libp2p) (*)
│   ├── libp2p-mdns v0.37.0 (/home/u/nimiq/rust-libp2p/protocols/mdns)
```

> 3. Rustfmt doesn't seem to be happy with the changes, please fix that :)

Done.

2022-05-12 04:03 UTC, thomaseizinger approved these changes

2022-05-12 04:05 UTC, merged

2022-05-12 09:43 UTC, mxinden commented
Thanks @hrxi!