README: Point to security@libp2p.io
libp2p/rust-libp2p pull request #2799
Opened 2022-08-05 06:11 UTC by mxinden

libp2p now has its own security mail address, namely security@libp2p.io.

No need to rely on security@ipfs.io any longer.

2022-08-05 07:05 UTC, thomaseizinger approved these changes

2022-08-05 09:00 UTC, elenaf9 requested changes
Nice! The bug-report template also contains the security e-mail and needs to be changed.
https://github.com/libp2p/rust-libp2p/blob/028decec6913f33b49bffb8cbfa7202629b2c22f/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L8

2022-08-08 06:18 UTC, mxinden commented
Good catch. Thanks @elenaf9.

2022-08-08 08:51 UTC, elenaf9 approved these changes

2022-08-08 08:57 UTC, merged