Minor refactor
libp2p/rust-libp2p pull request #3293
Opened 2023-01-01 14:49 UTC by yjhmelody

## Description

- Format code and improve docs.
- Rename some modules to keep the same style.
- Define `MapErrFuture` to keep the same code style.

## Notes

## Links to any relevant issues

## Open Questions

## Change checklist

- [] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

2023-01-02 13:09 UTC, jxs reviewed
Hi, and thanks for your interest! Overall looks good, can we maintain the function order for less diffs?

2023-01-09 01:03 UTC, thomaseizinger requested changes
Thanks!

There are several unrelated things happening here. We squash merge PRs so I'd appreciate it if we can split those i.e. do a separate PR for reordering the functions etc

2023-01-09 01:03 UTC, thomaseizinger commented on core/src/transport.rs
> +pub mod or;
This is a breaking change. I'd like to have this non-breaking please. Should be easy with another module and type aliases.

2023-01-09 01:03 UTC, thomaseizinger commented on core/src/transport/and_then.rs
> -            _marker: PhantomPinned,
Is this safe? I am sure this wasn't added without reason.

@mxinden Do you know why we phantom pin this type?

2023-01-09 01:03 UTC, thomaseizinger commented on core/src/transport/map_err.rs
> +pub struct MapErrFuture<T, Fut, F> {
This is also breaking. Please add a type alias to make it non-breaking with a deprecation attribute.

2023-05-02 20:05 UTC, thomaseizinger commented
Closing due to inactivity.

2023-05-02 20:05 UTC, closed without merging