fix(kad): close progress whenever closer in range
libp2p/rust-libp2p pull request #4934
Opened 2023-11-27 14:20 UTC by maqi

`Closer` shall be calculated as `closer to the seen num_results peers`,
not just to be `being the closest` as current.

This is in parallel to the PR https://github.com/libp2p/rust-libp2p/pull/4932
Split them into two to make the work easier to be discussed and reviewed.

## Description

## Notes & open questions

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

2023-12-05 13:09 UTC, maqi commented
> This pull request has merge conflicts. Could you please resolve them @maqi? 🙏

PR is updated, sorry for the delay

2023-12-05 13:18 UTC, maqi commented
Hi, @mxinden ,

here is the follow up fix in parallel to the PR https://github.com/libp2p/rust-libp2p/pull/4932

let me know if it make sense.
thx

2024-03-14 16:32 UTC, guillaumemichel requested changes
Thanks @maqi for looking into this, it is an important issue!

2024-03-14 16:32 UTC, guillaumemichel commented on protocols/kad/src/query/peers/closest.rs
> +        }
```suggestion
        let num_results = self.config.num_results.get();
        // furthest_peer is the furthest peer in range among the closest_peers
        let furthest_peer = self
            .closest_peers
            .iter()
            .enumerate()
            .nth(num_results - 1)
            .map(|(_, peer)| peer)
            .or_else(|| self.closest_peers.iter().last());

        if let Some((dist, _)) = furthest_peer {
            cur_range = *dist;
        }
```

2024-03-14 16:32 UTC, guillaumemichel commented on protocols/kad/src/query/peers/closest.rs
> +            progress = distance < cur_range || progress;
We also need to make sure that the peers with `distance < cur_range` are new (not already in `self.closest_peers`). If all `closer_peers` are already known, the query doesn't progress

2024-04-03 06:17 UTC, maqi commented
Hi, @guillaumemichel ,

Really appreciate your comments and suggestions.

Sorry for the late reply, have not check back this crate for a while as had been a while not receive any feedback.

Thx again and hope this PR could be merged soon.

Best Regards,

2024-04-03 06:31 UTC, maqi commented
The failing clippy as at https://github.com/libp2p/rust-libp2p/actions/runs/8534098889/job/23377901550?pr=4934
seems not related to this PR ?

2024-04-03 07:38 UTC, guillaumemichel approved these changes
Looks good to me! Thanks for your contribution @maqi!

2024-04-03 07:39 UTC, merged