fix(websocket-websys): change close code in drop implementation to 1000
libp2p/rust-libp2p pull request #5229
Opened 2024-03-14 21:20 UTC by sisou

## Description

In browsers, only the code 1000 and codes between 3000-4999 are allowed to be set by userland code: https://websockets.spec.whatwg.org/#dom-websocket-close

I found this while debugging use-after-free errors in our WASM application. Turns out, when connections are timing out, libp2p in rust drops them, but does not seem to close them explicitly (we are using libp2p-swarm). This led to these WebSockets still emitting events, the handlers of which were already dropped on the rust side, though.

A long investigation led me to have a look into the `Result` that gets returned from `close_with_code_and_reason`, and it turns out it's an error! Specifically:
```
InvalidAccessError: Failed to execute 'close' on 'WebSocket': The code must be either 1000, or between 3000 and 4999. 1001 is neither.
```

This PR only fixes the failing closing of the WebSocket, not the remaining use-after-free problem.

## Notes & open questions

Calling `.close()` on the WebSocket leads to the WebSocket still emitting its `"close"` event, for which the `websocket-websys`  transport registers a handler. This handler is dropped though together with the connection, so when the event comes around, the handler is no longer there and this error is thrown (by wasm-bindgen?):
```
Error: closure invoked recursively or after being dropped
```

This error is not critical in browsers (only annoying in the console) but exits NodeJS programs due to an uncaught exception.

A quick-fix would be to unregister the event handlers (or only the `onclose` handler) in the `Drop` implementation as well.

According to @nibhar, there must be a better way, though. He suggests storing the sockets event handlers outside the connection, having them clean-up themselves when the onclose or onerror handlers are called.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

2024-03-15 10:21 UTC, sisou commented
Here is a basic reproduction which I used to create this PR: https://github.com/sisou/libp2p-websocket-reproduction

2024-03-18 15:12 UTC, jxs requested changes
Hi, and thanks for the thorough report! Looks good to me, can you also add an entry in the `CHANGELOG.md`?
 cc @thomaseizinger you were the one adding the code, you may want to review it, and probably have an opinion on the use after free situation.

2024-03-19 04:22 UTC, thomaseizinger approved these changes
Wow, that is surprising!

Great find. Yeah needs a version bump and changelog entry.

2024-03-22 19:35 UTC, jsdanielh commented
> Wow, that is surprising!
> 
> Great find. Yeah needs a version bump and changelog entry.

Thanks for reviewing it. We just added the version bump and changelog entry.

2024-03-23 10:27 UTC, jxs approved these changes

2024-03-23 10:27 UTC, jxs commented on transports/websocket-websys/CHANGELOG.md
> +- Change close code in drop implementation to `1000` given than in browsers only
```suggestion
- Change close code in drop implementation to `1000` given that in browsers only
```

2024-03-23 20:32 UTC, jxs commented
Thanks! Just waiting on https://github.com/libp2p/rust-libp2p/pull/5253 so we can get CI green again

2024-03-25 11:12 UTC, jxs approved these changes

2024-03-25 13:20 UTC, merged

2024-03-25 14:20 UTC, jxs commented
@jsdanielh do you require a release?

2024-03-25 15:12 UTC, jsdanielh commented
> @jsdanielh do you require a release?

Yeah, that would be great

2024-05-01 20:05 UTC, jxs commented
sorry for the delay @jsdanielh and thanks for your patience.
A `libp2p-websocket-websys` version has now been released, see https://github.com/libp2p/rust-libp2p/discussions/5351 for more information.