feat(ping): impose `Sync` bound to `ping::Failure::Other`
libp2p/rust-libp2p pull request #5250
Opened 2024-03-21 07:05 UTC by drHuangMHT

## Description

Allow `ping::Event` to be shared between threads, instead of only sending between threads but no sharing.
This make it possible to send `ping::Event` through broadcast-style channels, like `tokio::sync::broadcast`.

## Notes & open questions

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

2024-03-25 19:00 UTC, jxs requested changes
LGTM, can you add a changelog entry and version bump?
Thanks!

2024-03-26 03:50 UTC, drHuangMHT commented
> LGTM, can you add a changelog entry and minor version bump? Thanks!

Um... Bumping from `0.44.0` to `0.45.0`? I'm seeing empty entry for `0.44.0`.

2024-04-05 11:48 UTC, jxs reviewed
> Um... Bumping from 0.44.0 to 0.45.0? I'm seeing empty entry for 0.44.0.

Yeah, thanks for mentioning, you are right `0.44.0` is empty on the `CHANGELOG.md` but [it was released](https://crates.io/crates/libp2p-ping/0.44.0) I will look into that!

2024-04-05 11:48 UTC, jxs commented on protocols/ping/CHANGELOG.md
> +## 0.45.0
```suggestion
## 0.44.1 - unreleased
```
I think this can be a minor version bump as `Failure::other()`  is only called internally, `cargo-semver-checks` also [confirms it](https://github.com/libp2p/rust-libp2p/actions/runs/8563934679/job/23469703665?pr=5250)

2024-04-05 11:48 UTC, jxs commented on Cargo.toml
> +libp2p-ping = { version = "0.45.0", path = "protocols/ping" }
```suggestion
libp2p-ping = { version = "0.44.1", path = "protocols/ping" }
```

2024-04-05 11:48 UTC, jxs commented on protocols/ping/Cargo.toml
> +version = "0.45.0"
```suggestion
version = "0.44.1"
```

2024-04-05 12:13 UTC, jxs commented
ok so, the `0.44.0` header was added on https://github.com/libp2p/rust-libp2p/commit/2a7291acfeb23ebe9105a0d7ee1c86d11aec35ec  and on https://github.com/libp2p/rust-libp2p/commit/74e315719cb4f934ba9b7052b8bc5e565dda3599 it was released along with other crates in the same state like `upnp`

2024-04-05 13:38 UTC, jxs approved these changes

2024-04-05 13:38 UTC, merged