chore(webtransport-websys): Change logs to debug level
libp2p/rust-libp2p pull request #5396
Opened 2024-05-17 12:58 UTC by oblique

## Description

When you enable Kademlia in a large network that uses multiple type of transports, then this log creates a very noisy console and makes meaningful logs hard to see.

We can also remove the log entirely if you prefer. Check: https://github.com/libp2p/rust-libp2p/pull/4015#discussion_r1229951440, https://github.com/libp2p/rust-libp2p/issues/4072, https://github.com/libp2p/rust-libp2p/pull/4133

## Notes & open questions

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

2024-05-17 16:42 UTC, zvolin approved these changes
can confirm, it's really noisy

2024-05-17 16:42 UTC, zvolin commented on transports/webtransport-websys/CHANGELOG.md
> +* Increase logs to debug level.
```suggestion
* Decrease logs to debug level.
```

2024-05-19 05:00 UTC, dariusc93 requested changes

2024-05-19 05:00 UTC, dariusc93 commented on transports/webtransport-websys/CHANGELOG.md
> +<<<<<<< HEAD
Looks like a bad merge?

2024-05-20 09:41 UTC, oblique commented on transports/webtransport-websys/CHANGELOG.md
> +<<<<<<< HEAD
oops. sorry. fixed

2024-05-20 10:56 UTC, oblique commented
For some reason CI got stuck

2024-05-20 11:51 UTC, jxs reviewed
Thanks for this. Interesting `cargo-semver-checks` does not complain, in fact I'd be more comfortable releasing this as a new minor wdyt?

2024-05-20 12:04 UTC, oblique commented
Do you mean 0.3.0? I'm ok with it.

2024-05-20 12:34 UTC, jxs commented
> Do you mean 0.3.0? I'm ok with it.

yeah exactly, ok thanks

2024-05-20 12:49 UTC, oblique commented
Question: In that case we will need to wait for libp2p 0.54 to incorporate this and #5390 in our crate. Do you have an approximate date for the release? Do you work with release cycles?

2024-05-22 12:55 UTC, jxs commented
> Question: In that case we will need to wait for libp2p 0.54 to incorporate this and #5390 in our crate. Do you have an approximate date for the release? Do you work with release cycles?

we're waiting on https://github.com/libp2p/rust-libp2p/issues/5389 to release a new `libp2p` version, but meanwhile I can release `libp2p-webtransport-websys` and I think you can then depend on it directly, wdyt?

2024-05-22 14:37 UTC, oblique commented
Sounds good!

2024-05-26 16:44 UTC, jxs approved these changes
LGTM

2024-05-26 16:45 UTC, merged

2024-05-26 20:33 UTC, jxs commented
@oblique released `libp2p-webtransport-sys`  [0.3.0](https://crates.io/crates/libp2p-webtransport-websys)