fix: libp2p-tls was not using libp2p-core from repository
libp2p/rust-libp2p pull request #5452
Opened 2024-06-07 13:46 UTC by oblique

While I was inspecting `cargo tree` I noticed that libp2p-tls was using crates.io instead of the developement repository.

## Description

## Notes & open questions

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

2024-06-07 20:48 UTC, jxs requested changes
Thanks for this Yianis, we don't require a changelog entry as nothing changes for the end user, can you update it please?

2024-06-07 21:45 UTC, oblique commented
I removed the changelog and version changes, however now the CI give this error:

```
Files in /home/runner/work/rust-libp2p/rust-libp2p/transports/quic have changed, please write a changelog entry in /home/runner/work/rust-libp2p/rust-libp2p/transports/quic/CHANGELOG.md
```

2024-06-08 00:38 UTC, jxs approved these changes

2024-06-08 00:38 UTC, jxs commented
> I removed the changelog and version changes, however now the CI give this error:
> 
> ```
> Files in /home/runner/work/rust-libp2p/rust-libp2p/transports/quic have changed, please write a changelog entry in /home/runner/work/rust-libp2p/rust-libp2p/transports/quic/CHANGELOG.md
> ```

yeah it's because you titled it as `fix` see [here](https://github.com/libp2p/rust-libp2p/blob/master/.github/workflows/ci.yml#L91-L98)

2024-06-08 00:39 UTC, merged