feat(kad): Return multiaddrs alognside peer IDs
libp2p/rust-libp2p pull request #5475
Opened 2024-06-19 19:02 UTC by Wiezzel

## Description

## Notes & open questions

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

2024-06-19 19:05 UTC, Wiezzel commented
@guillaumemichel

2024-06-20 09:32 UTC, guillaumemichel requested changes

2024-06-20 09:32 UTC, guillaumemichel commented on protocols/kad/src/behaviour.rs
> +pub struct FoundPeer {
This new struct can probably be used by other protocols, so we could define it in [peer_id.rs](https://github.com/libp2p/rust-libp2p/blob/32e917ffb26a5c176691602b8e315b570be37211/identity/src/peer_id.rs#L223) (or another location outside of `kad`) and name it `PeerInfo` ([reason](https://docs.libp2p.io/concepts/fundamentals/peers/#peer-info)). WDYT?

2024-06-20 09:32 UTC, guillaumemichel commented on protocols/kad/src/behaviour.rs
> +                            .expect("peer not present in address map")
We probably don't want to panic here
```suggestion
                            .unwrap_or_default()
```

2024-06-20 13:36 UTC, Wiezzel commented on protocols/kad/src/behaviour.rs
> +                            .expect("peer not present in address map")
Right, I fixed it in the ok case, but forgot about this one.

2024-06-20 13:38 UTC, Wiezzel commented on protocols/kad/src/behaviour.rs
> +pub struct FoundPeer {
Fair enough. Will do.

2024-06-21 07:22 UTC, Wiezzel commented on protocols/kad/src/behaviour.rs
> +pub struct FoundPeer {
I've moved it to `libp2p-core`, because `Multiaddr` cannot be imported in `libp2p-identity` due to dependency cycle.

2024-06-21 11:02 UTC, guillaumemichel approved these changes
Looks good, thank you @Wiezzel!

2024-06-21 11:03 UTC, merged

2024-06-21 12:15 UTC, stormshield-frb commented
Sorry to review after merge but why increase the version of `libp2p-kad` to `0.47.0` ? The `0.46.0` is not released yet if I am not mistaken.

2024-06-21 12:19 UTC, Wiezzel commented
@stormshield-frb I'm sorry. I'm no up-to-date with the release schedule.

2024-06-21 12:24 UTC, guillaumemichel commented
> Sorry to review after merge but why increase the version of libp2p-kad to 0.47.0 ? The 0.46.0 is not released yet if I am not mistaken. Same thing for the libp2p-core.

Good point! We'll address it in a follow up PR shortly.