chore: update MSRV
libp2p/rust-libp2p pull request #5650
Opened 2024-10-25 13:27 UTC by jxs

2024-10-25 14:10 UTC, dariusc93 approved these changes
I believe we would need to bump the minor version would we not? Besides that I do agree with the bump in msrv

2024-10-25 16:42 UTC, jxs commented
> I believe we would need to bump the minor version would we not? Besides that I do agree with the bump in msrv

right let's wait for the next major version release cycle before merging this, thanks Darius!

2024-10-25 19:17 UTC, dariusc93 commented
Will mark this as a draft for now until the next window

2024-10-29 08:29 UTC, guillaumemichel approved these changes

2024-12-11 11:57 UTC, elenaf9 reviewed
Any objection for this? @jxs

Would love to be able to use `expect`, e.g. in #5242, but that requires v1.81.

2024-12-11 11:57 UTC, elenaf9 commented on Cargo.toml
> +rust-version = "1.80.0"
```suggestion
rust-version = "1.83.0"
```

2024-12-14 07:25 UTC, elenaf9 approved these changes

2024-12-16 10:33 UTC, jxs commented
The thing with this PR is that I feel it's a breaking change. If someone is depending on `libp2p` `0.54.0` with say `Rust` version `0.75` then `cargo` will update it to `0.54.1` and it will stop compiling right?
With that in mind, does it make sense to release a new minor where the only change is that?

2024-12-17 09:30 UTC, elenaf9 commented
> The thing with this PR is that I feel it's a breaking change. If someone is depending on `libp2p` `0.54.0` with say `Rust` version `0.75` then `cargo` will update it to `0.54.1` and it will stop compiling right? With that in mind, does it make sense to release a new minor where the only change is that?

Hmm yeah good point. #4692 and #5266 both added a changelog entry for it, but bundled it in a existing minor release.

2024-12-17 09:31 UTC, elenaf9 requested changes
While reviewing #4692 and #5266 I noticed that they also changed the rust version in the Dockerfiles, so I think we need to do this here as well?

2024-12-17 11:45 UTC, dariusc93 commented
> The thing with this PR is that I feel it's a breaking change. If someone is depending on `libp2p` `0.54.0` with say `Rust` version `0.75` then `cargo` will update it to `0.54.1` and it will stop compiling right? With that in mind, does it make sense to release a new minor where the only change is that?

Correct. Generally, updating the msrv is a breaking change, which we would need to update the minor version of `rust-libp2p` if it's not done so already. And given that many protocols have a breaking change in it, it does feel appropriate for it to be `0.55.0`.

2024-12-18 12:00 UTC, jxs commented
glad we discuss this cause I was noticing yesterday, since we are updating `libp2p-gossipsub` to a new minor, `libp2p` consequentially also needs to be updated to a new minor right? If so everything's good and we can merge this, I'll add the `CHANGELOG.md` entry

2025-01-07 06:07 UTC, elenaf9 approved these changes
I think something went wrong in the rebase? PR suddenly has 71 commits.

But rest LGTM!

2025-01-08 19:32 UTC, merged